#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 <target_directory> <collection_array>" >&2
    exit 1
fi

target_dir="$1"
collection_array="$2"

mkdir -p "$target_dir"

while IFS= read -r -d '' dirpath; do
    output_file="$dirpath/meson.build"

    {
        echo "# This file is automatically generated from generate_meson_files.sh"
        echo

        for entry in "$dirpath"/*/; do
            [[ -d "$entry" ]] || continue
            dirname="$(basename "$entry")"
            echo "subdir('$dirname')"
        done
        echo

        echo "$collection_array += files("
        for entry in "$dirpath"/*; do
            [[ -f "$entry" ]] || continue
            filename="$(basename "$entry")"
            [[ "$filename" == "meson.build" ]] && continue
            [[ "$filename" == "main.cpp" ]] && continue
            echo "  '$filename',"
        done
        echo ")"
    } > "$output_file"
done < <(find "$target_dir" -type d -print0)
